"""all table

Revision ID: 15fe2d927908
Revises: 
Create Date: 2020-11-02 16:14:52.901438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fe2d927908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_name'), 'courier', ['name'], unique=True)
    op.create_index(op.f('ix_courier_tel'), 'courier', ['tel'], unique=True)
    op.create_table('metro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metro_station'), 'metro', ['station'], unique=True)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_name'), 'service', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.Column('metro', sa.String(length=64), nullable=True),
    sa.Column('exit_num', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(length=128), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=True)
    op.create_index(op.f('ix_client_tel'), 'client', ['tel'], unique=True)
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_num', sa.Integer(), nullable=True),
    sa.Column('delivery_cost', sa.Integer(), nullable=True),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_delivery_num'), 'delivery', ['delivery_num'], unique=True)
    op.create_index(op.f('ix_delivery_delivery_time'), 'delivery', ['delivery_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_delivery_time'), table_name='delivery')
    op.drop_index(op.f('ix_delivery_delivery_num'), table_name='delivery')
    op.drop_table('delivery')
    op.drop_index(op.f('ix_client_tel'), table_name='client')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_service_name'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_metro_station'), table_name='metro')
    op.drop_table('metro')
    op.drop_index(op.f('ix_courier_tel'), table_name='courier')
    op.drop_index(op.f('ix_courier_name'), table_name='courier')
    op.drop_table('courier')
    # ### end Alembic commands ###
